# -*- coding: utf-8 -*-
"""fix_dtype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3nvkvZoGATkWUE6lvXj640ScI4D5QmP
"""

import os
import numpy as np
from tqdm import tqdm

# This line defines tensor_dir — edit the path here if it ever changes.
tensor_dir = os.path.expanduser("~/ftzina_thesis/outputs/ALL_TENSORS_1/npy_files")

npy_files = sorted(f for f in os.listdir(tensor_dir) if f.endswith('.npy'))

converted, skipped = 0, 0
pbar = tqdm(npy_files, unit="file")
for fname in pbar:
    pbar.set_description(fname)
    fpath = os.path.join(tensor_dir, fname)
    t = np.load(fpath, mmap_mode='r')
    if t.dtype != np.float32:
        t32 = t.astype(np.float32)
        del t  # release the mmap before touching the file on disk

        tmp_path = fpath + '.tmp'
        np.save(tmp_path, t32)
        os.replace(tmp_path, fpath)  # atomic on POSIX
        converted += 1
    else:
        skipped += 1

print(f"\nDone. Converted: {converted}, already float32: {skipped}")
