# -*- coding: utf-8 -*-
"""heterogen_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0blYzEbqVrzMS7GdlNn5zJiK4BEP4uJ
"""

# @title
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  HETEROGENEITY ANALYSIS — Google Colab Version                             ║
# ║  Central vs. Peripheral CoLIAGe Radiomic Features — PDAC Cases            ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# HOW TO USE:
#   1. Upload this file to your Google Drive.
#   2. Open it in Colab (right-click → Open with → Google Colaboratory).
#   3. Edit the CONFIG section below with your actual Drive paths.
#   4. Run All Cells (Runtime → Run all).
#
# INPUT FILES (all in AGGREGATED_DIR):
#   central_vectors.npy       (N, 26) float32
#   peripheral_vectors.npy    (N, 26) float32
#   heterogeneity_vectors.npy (N, 26) float32   central - peripheral
#   case_ids.npy              (N,)    str
#   tumor_volumes.npy         (N,)    float32    optional — voxel counts
#
# OUTPUT (all saved to OUTPUT_DIR):
#   CSVs: paired t-tests, magnitude stats, PCA loadings, volume correlation
#   Plots: significance bars, distributions, magnitude histogram,
#          PCA scatter, volume correlation, feature heatmap

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_rel, wilcoxon, pearsonr, spearmanr
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

#%matplotlib inline
#plt.rcParams["figure.dpi"] = 120

import zipfile
import os

zip_file_path = '/content/drive/MyDrive/heterogeneity/aggregated.zip'
extract_to_path = '/content/drive/MyDrive/heterogeneity/aggregated'

try:
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        zip_ref.extractall(extract_to_path)
    print(f"Successfully unzipped '{zip_file_path}' to '{extract_to_path}'")
except FileNotFoundError:
    print(f"Error: The file '{zip_file_path}' was not found. Please check the path.")
except zipfile.BadZipFile:
    print(f"Error: '{zip_file_path}' is not a valid zip file or is corrupted.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

AGGREGATED_DIR = "/content/drive/MyDrive/heterogeneity/aggregated/aggregated"
OUTPUT_DIR     = "/content/drive/MyDrive/heterogeneity/analysis_results"
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(os.path.join(OUTPUT_DIR, "plots"), exist_ok=True)

a = np.load("/content/drive/MyDrive/heterogeneity/aggregated/aggregated/central_vectors.npy")
a.shape

b = np.load("/content/drive/MyDrive/heterogeneity/aggregated/aggregated/peripheral_vectors.npy")
b.shape

"""# ── CELL 4: Feature names"""

HARALICK_BASE = [
    "AngularSecondMoment",
    "Contrast",
    "Correlation",
    "SumOfSquaresVariance",
    "SumAverage",
    "SumVariance",
    "SumEntropy",
    "Entropy",
    "DifferenceVariance",
    "DifferenceEntropy",
    "InfoMeasureCorr1",
    "InfoMeasureCorr2",
    "MaximalCorrelationCoeff",
]
FEATURE_NAMES = (
    [f"{f}_Primary"   for f in HARALICK_BASE] +
    [f"{f}_Secondary" for f in HARALICK_BASE]
)
assert len(FEATURE_NAMES) == 26, f"Expected 26 feature names, got {len(FEATURE_NAMES)}"
print(f"Feature names defined: {len(FEATURE_NAMES)} features")

"""# ── CELL 5: Load aggregated arrays"""

print("\nLoading aggregated arrays...")

central    = np.load(os.path.join(AGGREGATED_DIR, "central_vectors.npy"))
peripheral = np.load(os.path.join(AGGREGATED_DIR, "peripheral_vectors.npy"))
heterog    = np.load(os.path.join(AGGREGATED_DIR, "heterogeneity_vectors.npy"))
case_ids   = np.load(os.path.join(AGGREGATED_DIR, "case_ids.npy"), allow_pickle=True)

####
# After loading, slice off the first column (CT intensity):
central    = central[:, 1:]      # (N, 26)
peripheral = peripheral[:, 1:]   # (N, 26)
heterog    = heterog[:, 1:]      # (N, 26)
print(f"  Dropped CT channel. Now {central.shape[1]} Haralick features per case.")
#####

assert central.shape == peripheral.shape == heterog.shape, \
    "central / peripheral / heterogeneity arrays must have the same shape."
assert central.shape[1] == 26, \
    f"Expected 26 features per case, got {central.shape[1]}."
assert len(case_ids) == central.shape[0], \
    "case_ids length must match number of cases in the feature arrays."

n_cases = central.shape[0]
print(f"  Cases loaded     : {n_cases}")
print(f"  Features per case: {central.shape[1]}")
print(f"  central.dtype    : {central.dtype}")
print(f"  peripheral.dtype : {peripheral.dtype}")

for name, arr in [("central", central), ("peripheral", peripheral), ("heterogeneity", heterog)]:
    n_nan = int(np.isnan(arr).sum())
    if n_nan > 0:
        print(f"  WARNING: {n_nan} NaN values in {name} array.")
    else:
        print(f"  {name}: no NaN values.")

# Optional tumor volumes
vol_path = os.path.join(AGGREGATED_DIR, "tumor_volumes.npy")
tumor_volumes = None
if os.path.exists(vol_path):
    tumor_volumes = np.load(vol_path).astype(np.float32)
    assert len(tumor_volumes) == n_cases, \
        "tumor_volumes.npy must have same number of entries as case_ids."
    print(f"  Tumor volumes    : loaded  (mean={tumor_volumes.mean():.0f} mm³ = "
          f"{tumor_volumes.mean()/1000:.1f} cm³)")
else:
    print("  tumor_volumes.npy: NOT FOUND — volume correlation will be skipped.")
    print("  To enable: save an (N,) float32 array of mask voxel counts to AGGREGATED_DIR.")

"""# ── CELL 6: Helper functions"""

def apply_bonferroni(p_values, n_tests=None):
    n = n_tests or len(p_values)
    return np.clip(np.array(p_values) * n, 0, 1)

def cohens_d_paired(a, b):
    diff = a - b
    return diff.mean() / (diff.std(ddof=1) + 1e-12)

def save_fig(fig, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fig.savefig(path, dpi=150, bbox_inches="tight")
    print(f"  Saved: {path}")

"""# ── CELL 7: Analysis 1 — Paired t-tests per feature"""

print("ANALYSIS 1: Paired t-tests (central vs. peripheral)")

n_features = len(FEATURE_NAMES)
ttest_results = []

for i, fname in enumerate(FEATURE_NAMES):
    c = central[:, i]
    p = peripheral[:, i]

    # Drop NaN pairs (affect this feature only)
    valid = np.isfinite(c) & np.isfinite(p)
    c, p = c[valid], p[valid]

    t_stat, p_ttest = ttest_rel(c, p)
    try:
        w_stat, p_wilcox = wilcoxon(c - p)
    except ValueError:
        w_stat, p_wilcox = np.nan, np.nan

    ttest_results.append({
        "feature"         : fname,
        "n_valid"         : int(valid.sum()),
        "mean_central"    : c.mean(),
        "mean_peripheral" : p.mean(),
        "mean_diff"       : (c - p).mean(),
        "std_diff"        : (c - p).std(ddof=1),
        "cohens_d"        : cohens_d_paired(c, p),
        "t_statistic"     : t_stat,
        "p_ttest_raw"     : p_ttest,
        "w_statistic"     : w_stat,
        "p_wilcox_raw"    : p_wilcox,
    })

df_tests = pd.DataFrame(ttest_results)
df_tests["p_ttest_bonferroni"]  = apply_bonferroni(df_tests["p_ttest_raw"].values, n_features)
df_tests["p_wilcox_bonferroni"] = apply_bonferroni(df_tests["p_wilcox_raw"].fillna(1).values, n_features)
df_tests["significant_ttest"]   = df_tests["p_ttest_bonferroni"]  < 0.05
df_tests["significant_wilcox"]  = df_tests["p_wilcox_bonferroni"] < 0.05
df_tests = df_tests.sort_values("p_ttest_bonferroni")

n_sig = int(df_tests["significant_ttest"].sum())
print(f"Features significantly different (Bonferroni t-test p<0.05): {n_sig}/{n_features}")
print(f"\nTop 5 most significant features:")
print(df_tests[["feature", "mean_diff", "cohens_d", "p_ttest_bonferroni",
                 "significant_ttest"]].head(5).to_string(index=False))

out_csv = os.path.join(OUTPUT_DIR, "heterogeneity_paired_ttests.csv")
df_tests.to_csv(out_csv, index=False)
print(f"\nFull results saved to: {out_csv}")

# Plot
fig, ax = plt.subplots(figsize=(14, 8))
log_p  = -np.log10(df_tests["p_ttest_bonferroni"].clip(lower=1e-10))
colors = ["tomato" if s else "steelblue" for s in df_tests["significant_ttest"]]
ax.barh(df_tests["feature"], log_p, color=colors, edgecolor="none")
ax.axvline(-np.log10(0.05), color="black", linestyle="--",
           linewidth=1.2, label="p = 0.05 (Bonferroni)")
ax.set_xlabel("-log₁₀(Bonferroni-corrected p-value)", fontsize=11)
ax.set_title("Central vs. Peripheral: Feature Significance\n"
             "(red = significant at α=0.05 after Bonferroni correction)",
             fontsize=12, fontweight="bold")
ax.tick_params(axis="y", labelsize=8)
ax.legend(fontsize=9)
plt.tight_layout()
save_fig(fig, os.path.join(OUTPUT_DIR, "plots", "01_paired_ttest_pvalues.png"))
plt.show()

"""# ── CELL 8: Analysis 2 — Per-feature distributions"""

print("ANALYSIS 2: Per-feature distributions — Central vs. Peripheral")

n_cols = 4
n_rows = (n_features + n_cols - 1) // n_cols
fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 4, n_rows * 3))
axes = axes.flatten()

for i, fname in enumerate(FEATURE_NAMES):
    ax = axes[i]
    ax.hist(central[:, i],    bins=25, alpha=0.6,
            color="steelblue",  label="Central",    density=True)
    ax.hist(peripheral[:, i], bins=25, alpha=0.6,
            color="darkorange", label="Peripheral",  density=True)
    ax.set_title(fname, fontsize=7, fontweight="bold")
    ax.tick_params(labelsize=6)
    if i == 0:
        ax.legend(fontsize=6)

for j in range(i + 1, len(axes)):
    axes[j].axis("off")

plt.suptitle("CoLIAGe Feature Distributions — Central vs. Peripheral (PDAC cases)",
             fontsize=12, fontweight="bold")
plt.tight_layout()
save_fig(fig, os.path.join(OUTPUT_DIR, "plots", "02_feature_distributions_central_vs_peripheral.png"))
plt.show()

"""# ── CELL 9: Analysis 3 — Heterogeneity magnitude"""

print("ANALYSIS 3: Heterogeneity magnitude (L2 norm of heterogeneity vector)")

magnitudes = np.linalg.norm(heterog, axis=1)

mag_stats = {
    "n_cases" : len(magnitudes),
    "mean"    : magnitudes.mean(),
    "std"     : magnitudes.std(ddof=1),
    "median"  : float(np.median(magnitudes)),
    "q25"     : float(np.percentile(magnitudes, 25)),
    "q75"     : float(np.percentile(magnitudes, 75)),
    "min"     : float(magnitudes.min()),
    "max"     : float(magnitudes.max()),
}

print(f"  Mean   : {mag_stats['mean']:.4f} ± {mag_stats['std']:.4f}")
print(f"  Median : {mag_stats['median']:.4f}")
print(f"  IQR    : [{mag_stats['q25']:.4f}, {mag_stats['q75']:.4f}]")
print(f"  Range  : [{mag_stats['min']:.4f}, {mag_stats['max']:.4f}]")

df_mag = pd.DataFrame([mag_stats])
out_csv = os.path.join(OUTPUT_DIR, "heterogeneity_magnitude_stats.csv")
df_mag.to_csv(out_csv, index=False)
print(f"  Saved: {out_csv}")

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

axes[0].hist(magnitudes, bins=30, color="mediumpurple", edgecolor="white", alpha=0.85)
axes[0].axvline(magnitudes.mean(),       color="tomato", linestyle="--", linewidth=1.8,
                label=f"Mean = {magnitudes.mean():.3f}")
axes[0].axvline(float(np.median(magnitudes)), color="navy",  linestyle=":",  linewidth=1.8,
                label=f"Median = {float(np.median(magnitudes)):.3f}")
axes[0].set_xlabel("Heterogeneity Magnitude (L2 norm)", fontsize=10)
axes[0].set_ylabel("Count", fontsize=10)
axes[0].set_title("Distribution of Intra-Tumor\nHeterogeneity Across PDAC Cases", fontsize=11)
axes[0].legend(fontsize=9)

sorted_mag = np.sort(magnitudes)
axes[1].plot(sorted_mag, color="mediumpurple", linewidth=1.5)
axes[1].fill_between(range(len(sorted_mag)), sorted_mag, alpha=0.2, color="mediumpurple")
axes[1].set_xlabel("Case rank (sorted by magnitude)", fontsize=10)
axes[1].set_ylabel("Heterogeneity Magnitude", fontsize=10)
axes[1].set_title("Sorted Heterogeneity Magnitudes\n(each point = one PDAC case)", fontsize=11)

plt.suptitle("Intra-Tumor Heterogeneity Magnitude Analysis", fontsize=12, fontweight="bold")
plt.tight_layout()
save_fig(fig, os.path.join(OUTPUT_DIR, "plots", "03_heterogeneity_magnitude_distribution.png"))
plt.show()

"""# ── CELL 10: Analysis 4 — PCA"""

print("ANALYSIS 4: PCA on heterogeneity vectors")

scaler   = StandardScaler()
H_scaled = scaler.fit_transform(heterog)

n_components = min(10, H_scaled.shape[1])
pca    = PCA(n_components=n_components)
coords = pca.fit_transform(H_scaled)

explained  = pca.explained_variance_ratio_
cumulative = np.cumsum(explained)

print(f"  PC1 explains      : {explained[0]*100:.1f}% variance")
print(f"  PC1+PC2 explain   : {cumulative[1]*100:.1f}% variance")
print(f"  PCs for 80% total : {int(np.searchsorted(cumulative, 0.80)) + 1}")

loadings_df = pd.DataFrame(
    pca.components_.T,
    index=FEATURE_NAMES,
    columns=[f"PC{i+1}" for i in range(pca.n_components_)]
)
out_csv = os.path.join(OUTPUT_DIR, "heterogeneity_pca_components.csv")
loadings_df.to_csv(out_csv)
print(f"  PCA loadings saved: {out_csv}")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].bar(range(1, len(explained)+1), explained * 100,
            color="steelblue", alpha=0.8, label="Individual")
axes[0].step(range(1, len(cumulative)+1), cumulative * 100,
             color="tomato", linewidth=2, label="Cumulative")
axes[0].axhline(80, color="gray", linestyle="--", linewidth=1, alpha=0.7, label="80% threshold")
axes[0].set_xlabel("Principal Component", fontsize=10)
axes[0].set_ylabel("Explained Variance (%)", fontsize=10)
axes[0].set_title("PCA Scree Plot — Heterogeneity Space", fontsize=11)
axes[0].legend(fontsize=9)
axes[0].set_xticks(range(1, len(explained)+1))

axes[1].scatter(coords[:, 0], coords[:, 1],
                alpha=0.5, s=20, color="mediumpurple", edgecolors="none")
axes[1].set_xlabel(f"PC1 ({explained[0]*100:.1f}%)", fontsize=10)
axes[1].set_ylabel(f"PC2 ({explained[1]*100:.1f}%)", fontsize=10)
axes[1].set_title("PDAC Cases in Heterogeneity PCA Space\n(each point = one tumor)", fontsize=11)

plt.suptitle("PCA of Intra-Tumor Heterogeneity Vectors", fontsize=12, fontweight="bold")
plt.tight_layout()
save_fig(fig, os.path.join(OUTPUT_DIR, "plots", "04_pca_heterogeneity_space.png"))
plt.show()

"""# ── CELL 11: Analysis 5 — Correlation with tumor volume (optional)"""

if tumor_volumes is not None:
    print("ANALYSIS 5: Heterogeneity magnitude vs. tumor volume")

    r_pearson,  p_pearson  = pearsonr(magnitudes,  tumor_volumes)
    r_spearman, p_spearman = spearmanr(magnitudes, tumor_volumes)

    print(f"  Pearson  r = {r_pearson:.3f}   p = {p_pearson:.4f}")
    print(f"  Spearman r = {r_spearman:.3f}   p = {p_spearman:.4f}")

    df_vol = pd.DataFrame({
        "metric"  : ["Pearson", "Spearman"],
        "r"       : [r_pearson,  r_spearman],
        "p_value" : [p_pearson,  p_spearman],
        "n_cases" : [len(magnitudes), len(magnitudes)],
    })
    out_csv = os.path.join(OUTPUT_DIR, "heterogeneity_correlation_with_volume.csv")
    df_vol.to_csv(out_csv, index=False)
    print(f"  Saved: {out_csv}")

    vols_cm3 = tumor_volumes / 1000   # mm³ → cm³
    m, b = np.polyfit(vols_cm3, magnitudes, 1)
    x_line = np.linspace(vols_cm3.min(), vols_cm3.max(), 200)

    fig, ax = plt.subplots(figsize=(7, 6))
    ax.scatter(vols_cm3, magnitudes, alpha=0.45, s=18,
               color="steelblue", edgecolors="none")
    ax.plot(x_line, m * x_line + b, color="tomato", linewidth=2,
            label=f"Pearson r = {r_pearson:.3f}, p = {p_pearson:.3f}\n"
                  f"Spearman r = {r_spearman:.3f}, p = {p_spearman:.3f}")
    ax.set_xlabel("Tumor Volume (cm³)", fontsize=11)
    ax.set_ylabel("Heterogeneity Magnitude (L2 norm)", fontsize=11)
    ax.set_title("Intra-Tumor Heterogeneity vs. Tumor Size\n(PDAC cases)", fontsize=12)
    ax.legend(fontsize=9)
    plt.tight_layout()
    save_fig(fig, os.path.join(OUTPUT_DIR, "plots", "05_correlation_with_volume.png"))
    plt.show()
else:
    print("Skipping Analysis 5 (no tumor_volumes.npy found).")

"""# ── CELL 12: Analysis 6 — Feature heatmap"""

print("ANALYSIS 6: Feature mean heatmap — Central vs. Peripheral")

mean_central    = central.mean(axis=0)
mean_peripheral = peripheral.mean(axis=0)
mean_diff       = mean_central - mean_peripheral

df_heat = pd.DataFrame({
    "Central"    : mean_central,
    "Peripheral" : mean_peripheral,
    "Difference" : mean_diff,
}, index=FEATURE_NAMES)

fig, axes = plt.subplots(1, 3, figsize=(16, 10))
for ax, col, title, cmap in zip(
    axes,
    ["Central", "Peripheral", "Difference"],
    ["Mean Central", "Mean Peripheral", "Difference (C − P)"],
    ["Blues", "Oranges", "coolwarm"]
):
    center = 0 if col == "Difference" else None
    sns.heatmap(
        df_heat[[col]], ax=ax, cmap=cmap, center=center,
        yticklabels=FEATURE_NAMES, xticklabels=[col],
        annot=True, fmt=".3f", annot_kws={"size": 7},
        cbar_kws={"shrink": 0.6}
    )
    ax.set_title(title, fontsize=11, fontweight="bold")
    ax.tick_params(axis="y", labelsize=7)

plt.suptitle("Mean CoLIAGe Feature Values: Central vs. Peripheral\n(PDAC cohort)",
             fontsize=13, fontweight="bold")
plt.tight_layout()
save_fig(fig, os.path.join(OUTPUT_DIR, "plots", "06_feature_heatmap_central_vs_peripheral.png"))
plt.show()

"""# ── CELL 13: Final summary"""

print("HETEROGENEITY ANALYSIS COMPLETE")
print(f"  Cases analyzed                    : {n_cases}")
print(f"  Significant features (Bonferroni) : {int(df_tests['significant_ttest'].sum())}/26")
print(f"  Mean heterogeneity magnitude      : {magnitudes.mean():.4f} ± {magnitudes.std(ddof=1):.4f}")
print(f"  Outputs saved to                  : {OUTPUT_DIR}")
print("="*60)
print("\nFiles produced:")
for f in sorted(os.listdir(OUTPUT_DIR)):
    if f.endswith(".csv"):
        print(f"  {f}")
print("  plots/")
for f in sorted(os.listdir(os.path.join(OUTPUT_DIR, "plots"))):
    print(f"    {f}")