# -*- coding: utf-8 -*-
"""merge_batches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzVPbz5rCFgh6K3TOi7K34b94_FpNCn9
"""

# merge_batches.py — run once after all batches finish
import numpy as np
import os

OUTPUT_DIR = "/path/to/step1_outputs"
BATCH_NAMES = ["batch_1", "batch_2", "batch_3", "batch_4"]

X_list   = []
y_list   = []
ids_list = []

print("=" * 60)
print("Loading per-batch arrays...")
print("=" * 60)

for batch in BATCH_NAMES:
    x_path   = os.path.join(OUTPUT_DIR, f"master_X_{batch}.npy")
    y_path   = os.path.join(OUTPUT_DIR, f"master_y_{batch}.npy")
    ids_path = os.path.join(OUTPUT_DIR, f"master_ids_{batch}.npy")

    # Confirm all three files exist before loading anything
    for p in [x_path, y_path, ids_path]:
        assert os.path.exists(p), f"Missing file: {p}"

    X_b   = np.load(x_path)
    y_b   = np.load(y_path)
    ids_b = np.load(ids_path, allow_pickle=True)

    # Per-batch internal consistency
    assert X_b.shape[0] == y_b.shape[0] == ids_b.shape[0], (
        f"{batch}: mismatched row counts — "
        f"X={X_b.shape[0]}, y={y_b.shape[0]}, ids={ids_b.shape[0]}"
    )
    assert X_b.ndim == 2, \
        f"{batch}: X array is not 2D — got shape {X_b.shape}"
    assert y_b.ndim == 1, \
        f"{batch}: y array is not 1D — got shape {y_b.shape}"

    print(f"  {batch}: {X_b.shape[0]} cases, "
          f"{X_b.shape[1]} features, "
          f"PDAC={int((y_b==1).sum())}, "
          f"non-PDAC={int((y_b==0).sum())}, "
          f"dtype X={X_b.dtype}")

    X_list.append(X_b)
    y_list.append(y_b)
    ids_list.append(ids_b)

print()

# ── Feature dimension consistency across batches ──────────────────────────────
feature_dims = [X.shape[1] for X in X_list]
assert len(set(feature_dims)) == 1, (
    f"Feature dimension mismatch across batches: "
    f"{dict(zip(BATCH_NAMES, feature_dims))} — "
    f"all batches must have been processed with the same step1 configuration."
)
print(f"Feature dimension consistent across all batches: {feature_dims[0]}")

# ── Concatenate ───────────────────────────────────────────────────────────────
X_master   = np.concatenate(X_list,   axis=0)
y_master   = np.concatenate(y_list,   axis=0)
ids_master = np.concatenate(ids_list, axis=0)

# ── Row count sanity check ────────────────────────────────────────────────────
total_expected = sum(X.shape[0] for X in X_list)
assert X_master.shape[0] == total_expected, (
    f"Concatenation lost cases: expected {total_expected}, got {X_master.shape[0]}"
)

# ── Duplicate case ID check ───────────────────────────────────────────────────
ids_list_str = [str(i) for i in ids_master]
if len(ids_list_str) != len(set(ids_list_str)):
    from collections import Counter
    counts = Counter(ids_list_str)
    duplicates = {k: v for k, v in counts.items() if v > 1}
    raise AssertionError(
        f"Duplicate case IDs found across batches — "
        f"these cases appear more than once: {duplicates}\n"
        f"Check that your batch zips don't contain overlapping CT files."
    )
print("No duplicate case IDs across batches.")

# ── NaN / Inf check ──────────────────────────────────────────────────────────
nan_count = int(np.isnan(X_master).sum())
inf_count = int(np.isinf(X_master).sum())
if nan_count > 0:
    print(f"WARNING: {nan_count} NaN values found in X_master. "
          f"These will affect feature selection and model training.")
if inf_count > 0:
    print(f"WARNING: {inf_count} Inf values found in X_master.")
if nan_count == 0 and inf_count == 0:
    print("No NaN or Inf values in X_master.")

# ── Final summary ─────────────────────────────────────────────────────────────
print()
print("=" * 60)
print("MERGED MASTER DATASET SUMMARY")
print("=" * 60)
print(f"  Total cases  : {X_master.shape[0]}")
print(f"  Features     : {X_master.shape[1]}")
print(f"  PDAC         : {int((y_master==1).sum())}")
print(f"  non-PDAC     : {int((y_master==0).sum())}")
print(f"  Class balance: {int((y_master==1).sum()) / len(y_master) * 100:.1f}% PDAC")
print()

per_batch_total = [X.shape[0] for X in X_list]
for batch, n in zip(BATCH_NAMES, per_batch_total):
    print(f"  {batch}: {n} cases  "
          f"({n / X_master.shape[0] * 100:.1f}% of total)")

# ── Save ──────────────────────────────────────────────────────────────────────
print()
print("Saving merged arrays...")

np.save(os.path.join(OUTPUT_DIR, "master_X.npy"),
        X_master.astype(np.float32))
np.save(os.path.join(OUTPUT_DIR, "master_y.npy"),
        y_master.astype(np.int32))
np.save(os.path.join(OUTPUT_DIR, "master_ids.npy"),
        ids_master.astype(str))

print(f"  Saved master_X.npy   — shape {X_master.astype(np.float32).shape}, dtype float32")
print(f"  Saved master_y.npy   — shape {y_master.astype(np.int32).shape}, dtype int32")
print(f"  Saved master_ids.npy — {len(ids_master)} case IDs")
print()
print("Done. Proceed to step2_split.py.")