# -*- coding: utf-8 -*-
"""merge_batches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzVPbz5rCFgh6K3TOi7K34b94_FpNCn9
"""

# merge_batches.py — run once after all batches finish
import numpy as np
import os

OUTPUT_DIR  = "~/ftzina_thesis/outputs/step1"
BATCH_NAMES = ["batch_1", "batch_2", "batch_3", "batch_4"]  # adjust to your actual batches

X_list   = []
y_list   = []
ids_list = []

for batch in BATCH_NAMES:
    X_b   = np.load(os.path.join(OUTPUT_DIR, f"master_X_{batch}.npy"))
    y_b   = np.load(os.path.join(OUTPUT_DIR, f"master_y_{batch}.npy"))
    ids_b = np.load(os.path.join(OUTPUT_DIR, f"master_ids_{batch}.npy"),
                    allow_pickle=True)

    X_list.append(X_b)
    y_list.append(y_b)
    ids_list.append(ids_b)

    print(f"{batch}: {X_b.shape[0]} cases")

X_master   = np.concatenate(X_list,   axis=0)
y_master   = np.concatenate(y_list,   axis=0)
ids_master = np.concatenate(ids_list, axis=0)

print(f"\nMerged master: {X_master.shape}")
print(f"PDAC={int((y_master==1).sum())}  non-PDAC={int((y_master==0).sum())}")

# Sanity check: no duplicate case IDs
assert len(ids_master) == len(set(ids_master)), \
    "Duplicate case IDs found across batches!"

np.save(os.path.join(OUTPUT_DIR, "master_X.npy"),   X_master.astype(np.float32))
np.save(os.path.join(OUTPUT_DIR, "master_y.npy"),   y_master.astype(np.int32))
np.save(os.path.join(OUTPUT_DIR, "master_ids.npy"), ids_master.astype(str))
print("Saved master_X/y/ids.npy — proceed to step2.")