# -*- coding: utf-8 -*-
"""STEP 6+6b CNN TRAINING+evaluation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Y3l5eA-w1RBNM7rTms7Uis-i_kCDsbw

# STEP 6 — Patch-Based CNN Training (with Z-score normalization)

Input  : {case_id}_image.npy   (128,128,128)  raw CT volumes
         {case_id}_mask.npy    (128,128,128)  binary ROI masks  uint8
         ids_train/val/test.npy, y_train/val/test.npy  (from Step 2)
Output : best_cnn.pt
         deep_embeddings_train/val/test.npy   → (N, embed_dim)
         cnn_training_curves_MONAI.png
         zscore_stats.npz                     → CT_MEAN, CT_STD from training set

Patch strategy:
  - Training : 4 random patches per case sampled from within ROI voxels
  - Val/Test : 1 patch centered on ROI centroid (deterministic)
  - Patch size: 64³ voxels
  - Augmentation: random axis flips (train only)

Z-score normalization:
  - CT_MEAN and CT_STD are computed from ALL training-set image.npy files
    using a single pass (online sum / sum-of-squares accumulation).
  - Statistics are computed ONCE and saved to zscore_stats.npz so
    subsequent runs skip the scan.
  - Every CT patch is normalized as (patch - CT_MEAN) / CT_STD
    inside PatchDataset.__getitem__, applied AFTER patch extraction.
  - Val and test patches use the SAME training-set statistics
    (fit on train, transform all) — consistent with StandardScaler
    discipline in the radiomic branch.
  - CoLIAGe mode (USE_COLIAGE=True) skips Z-score normalization since
    Haralick texture maps are on their own scales.

Input modes:
  - USE_COLIAGE=False → raw CT, in_channels=1  (Z-score applied)
  - USE_COLIAGE=True  → CoLIAGe feature maps, in_channels=28  (no Z-score)

Simple3DCNN is a working placeholder. Replace with your own
architecture by dropping it into the same forward() signature.

# configure
"""

import os
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data   import Dataset, DataLoader
from sklearn.metrics    import roc_auc_score
import matplotlib
matplotlib.use("Agg")   # headless Linux: no display available, render straight to file
import matplotlib.pyplot as plt

# CONFIG — edit before running
IMAGE_DIR        = "/content/drive/MyDrive/metrics_batch1/ALL_METRICS_FULL/ALL_IMAGES_FULL"        # {case_id}_image.npy   (128,128,128)
MASK_DIR         = "/content/drive/MyDrive/metrics_batch1/ALL_METRICS_FULL/ALL_MASKS_FULL"         # {case_id}_mask.npy    (128,128,128)
# COLIAGE_DIR      = "/content/drive/MyDrive/metrics_batch1/ALL_TENSORS/npy files"       # {case_id}_coliage.npy (128,128,128,28)
SPLIT_DIR        = "/content/drive/MyDrive/metrics_batch1/step2_outputs"            # ids_*.npy, y_*.npy from Step 2
OUTPUT_DIR       = "/content/drive/MyDrive/metrics_batch1/step6_outputs"

USE_COLIAGE      = False    # True → 28-channel CoLIAGe input; False → 1-ch raw CT
COLIAGE_DIR      = None     # set path if USE_COLIAGE=True
PATCH_SIZE       = 64       # cubic patch side length in voxels
PATCHES_PER_CASE = 4        # patches sampled per case per epoch (train only)
EMBED_DIM        = 128      # CNN output embedding dimension
BATCH_SIZE       = 4        # keep small for 3D patches (memory)
N_EPOCHS         = 50
LR               = 1e-4
WEIGHT_DECAY     = 1e-4
PATIENCE         = 10       # early stopping on val AUC
RANDOM_STATE     = 42
NUM_WORKERS      = 2        # set 0 on Windows

# ── Z-score normalization ─────────────────────────────────────────────────────
# Z-score statistics (mean, std) are computed from TRAINING images ONLY,
# then applied consistently to val and test — fit on train, transform all.
# This file is saved after the first run so subsequent runs skip recomputation.
# Set to None to recompute from scratch.
APPLY_ZSCORE         = True
ZSCORE_STATS_FILE    = os.path.join(OUTPUT_DIR, "zscore_stats.npz")
# ─────────────────────────────────────────────────────────────────────────────

torch.manual_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Console -> file logging ────────────────────────────────────────────────
# No display on this machine, so mirror every print() to a .txt log as well
# as the terminal. Pull the log (and the saved .png files) off this machine
# afterward to inspect metrics / regenerate plots elsewhere.
import sys

class _Tee:
    def __init__(self, *streams):
        self.streams = streams
    def write(self, data):
        for s in self.streams:
            s.write(data)
            s.flush()
    def flush(self):
        for s in self.streams:
            s.flush()

LOG_FILE = os.path.join(OUTPUT_DIR, "step6_run_log.txt")
_log_fh  = open(LOG_FILE, "a", encoding="utf-8")
sys.stdout = _Tee(sys.__stdout__, _log_fh)
sys.stderr = _Tee(sys.__stderr__, _log_fh)
print(f"Logging console output to: {LOG_FILE}")
# ─────────────────────────────────────────────────────────────────────────────

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

"""# Patch utilities"""

def get_roi_centroid(mask: np.ndarray) -> np.ndarray:
    """
    Returns integer (y, x, z) centroid of a binary mask.
    mask: (H, W, D) uint8 or bool
    """
    coords = np.argwhere(mask.astype(bool))
    assert len(coords) > 0, "Empty mask — cannot compute centroid."
    return coords.mean(axis=0).astype(int)

def extract_patch(volume: np.ndarray,
                  center: np.ndarray,
                  patch_size: int = 64) -> np.ndarray:
    """
    Extract a cubic patch centered at `center` from `volume`.
    Zero-pads if patch extends beyond volume boundary.

    volume     : (H, W, D)        or (H, W, D, C)
    center     : (3,) int array   [y, x, z]
    patch_size : int

    Returns    : (P, P, P)        or (P, P, P, C)
    """
    H, W, D = volume.shape[:3]
    p  = patch_size // 2
    cy, cx, cz = int(center[0]), int(center[1]), int(center[2])

    y0, y1 = cy - p, cy + p
    x0, x1 = cx - p, cx + p
    z0, z1 = cz - p, cz + p

    y0c, y1c = max(0, y0), min(H, y1)
    x0c, x1c = max(0, x0), min(W, x1)
    z0c, z1c = max(0, z0), min(D, z1)

    crop = (volume[y0c:y1c, x0c:x1c, z0c:z1c]
            if volume.ndim == 3
            else volume[y0c:y1c, x0c:x1c, z0c:z1c, :])

    pad_w = [
        (y0c - y0, y1 - y1c),
        (x0c - x0, x1 - x1c),
        (z0c - z0, z1 - z1c),
    ]
    if volume.ndim == 4:
        pad_w.append((0, 0))

    return np.pad(crop, pad_w, mode="constant", constant_values=0)

def sample_random_roi_centers(mask: np.ndarray,
                               n_samples: int = 4,
                               patch_size: int = 64) -> list:
    """
    Sample n_samples random patch centers from within the ROI mask,
    filtered to only positions where a full patch fits inside the volume.

    Returns list of (y, x, z) integer arrays.
    """
    H, W, D = mask.shape
    p = patch_size // 2
    roi_coords = np.argwhere(mask.astype(bool))

    # Only keep centers where the patch fits entirely inside the volume
    valid = roi_coords[
        (roi_coords[:, 0] >= p) & (roi_coords[:, 0] < H - p) &
        (roi_coords[:, 1] >= p) & (roi_coords[:, 1] < W - p) &
        (roi_coords[:, 2] >= p) & (roi_coords[:, 2] < D - p)
    ]

    if len(valid) == 0:
        # ROI too small or too close to boundary — fall back to centroid
        return [get_roi_centroid(mask)]

    replace = len(valid) < n_samples
    idx = np.random.choice(len(valid), size=n_samples, replace=replace)
    return [valid[i] for i in idx]

"""# Dataset"""

class PatchDataset(Dataset):
    """
    Patch-based 3D dataset.

    For training   : samples PATCHES_PER_CASE random ROI patches per case.
    For val / test : extracts ONE centroid patch per case (deterministic).

    Parameters
    ----------
    case_ids         : list[str]
    labels           : dict {case_id: int}
    image_dir        : str  — directory with {case_id}_image.npy
    mask_dir         : str  — directory with {case_id}_mask.npy
    patch_size       : int
    patches_per_case : int  — set to 1 for val/test
    use_coliage      : bool — if True, load CoLIAGe as 28-channel input
    coliage_dir      : str  — directory with {case_id}_coliage.npy
    augment          : bool — random flips (training only)
    """
    def __init__(
        self,
        case_ids:         list,
        labels:           dict,
        image_dir:        str,
        mask_dir:         str,
        patch_size:       int   = 64,
        patches_per_case: int   = 4,
        use_coliage:      bool  = False,
        coliage_dir:      str   = None,
        augment:          bool  = False,
        ct_mean:          float = 0.0,
        ct_std:           float = 1.0,
    ):
        self.case_ids         = case_ids
        self.labels           = labels
        self.image_dir        = image_dir
        self.mask_dir         = mask_dir
        self.patch_size       = patch_size
        self.patches_per_case = patches_per_case
        self.use_coliage      = use_coliage
        self.coliage_dir      = coliage_dir
        self.augment          = augment
        self.is_single_patch  = (patches_per_case == 1)
        self.ct_mean          = ct_mean
        self.ct_std           = max(ct_std, 1e-8)   # avoid division by zero

        # Flat index: each entry is (case_id, patch_slot)
        self.index = [
            (cid, pi)
            for cid in case_ids
            for pi in range(patches_per_case)
        ]

    def __len__(self):
        return len(self.index)

    def __getitem__(self, idx):
        case_id, patch_slot = self.index[idx]
        label = self.labels[case_id]

        # ── Load mask ──────────────────────────────────────────────────────
        mask_path = os.path.join(self.mask_dir, f"{case_id}_mask.npy")
        mask = np.load(mask_path)                   # (128,128,128) uint8

        # ── Choose patch center ────────────────────────────────────────────
        if self.is_single_patch:
            # Deterministic: use ROI centroid (for val/test)
            center = get_roi_centroid(mask)
        else:
            # Random: sample from within ROI (for training)
            centers = sample_random_roi_centers(
                mask, n_samples=1, patch_size=self.patch_size
            )
            center = centers[0]

        # ── Load volume and extract patch ──────────────────────────────────
        if self.use_coliage:
            # CoLIAGe: (128,128,128,28) → patch (P,P,P,28) → (28,P,P,P)
            vol_path = os.path.join(self.coliage_dir, f"{case_id}_tensor_128_27ch.npy")
            volume   = np.load(vol_path).astype(np.float32)
            patch    = extract_patch(volume, center, self.patch_size)
            patch    = patch.transpose(3, 0, 1, 2)        # (28, P, P, P)
        else:
            # Raw CT: (128,128,128) → patch (P,P,P) → (1,P,P,P)
            vol_path = os.path.join(self.image_dir, f"{case_id}_image.npy")
            volume   = np.load(vol_path).astype(np.float32)
            patch    = extract_patch(volume, center, self.patch_size)

            # ── Z-score normalization using training-set statistics ────────
            # CT_MEAN and CT_STD were computed from training images only
            # and passed in via ct_mean / ct_std constructor arguments.
            # Normalizing here (after patch extraction) is equivalent to
            # normalizing the full volume — patches are sub-volumes of the
            # same intensity space.
            patch = (patch - self.ct_mean) / self.ct_std

            patch    = patch[np.newaxis, ...]              # (1, P, P, P)

        # ── Augmentation (training only) ───────────────────────────────────
        if self.augment:
            patch = self._random_flip(patch)

        return (
            torch.tensor(patch,         dtype=torch.float32),
            torch.tensor(label,         dtype=torch.float32),
            case_id,                                      # returned for tracking
        )

    @staticmethod
    def _random_flip(patch: np.ndarray) -> np.ndarray:
        """Random flip along each spatial axis (axes 1,2,3)."""
        for axis in [1, 2, 3]:
            if np.random.rand() > 0.5:
                patch = np.flip(patch, axis=axis).copy()
        return patch

"""# **Simple3DCNN**"""

# Model — Simple 3D CNN placeholder
# Replace self.encoder / embed_head with your real architecture.
# Keep the same forward() signature.

class Simple3DCNN(nn.Module):
    """
    Lightweight 3D CNN for patch classification and embedding extraction.

    Input : (batch, C_in, 64, 64, 64)
    Output: (batch,) logit         when return_embedding=False
            (batch, embed_dim)     when return_embedding=True
    """
    def __init__(self, in_channels: int = 1, embed_dim: int = 128):
        super().__init__()

        self.encoder = nn.Sequential(
            # Block 1: C × 64³ → 32 × 32³
            nn.Conv3d(in_channels, 32, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm3d(32), nn.ReLU(inplace=True),
            nn.MaxPool3d(2),

            # Block 2: 32 × 32³ → 64 × 16³
            nn.Conv3d(32, 64, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm3d(64), nn.ReLU(inplace=True),
            nn.MaxPool3d(2),

            # Block 3: 64 × 16³ → 128 × 8³
            nn.Conv3d(64, 128, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm3d(128), nn.ReLU(inplace=True),
            nn.MaxPool3d(2),

            # Block 4: 128 × 8³ → 256 × 4³
            nn.Conv3d(128, 256, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm3d(256), nn.ReLU(inplace=True),
            nn.MaxPool3d(2),
        )

        self.gap = nn.AdaptiveAvgPool3d(1)   # → (batch, 256, 1, 1, 1)

        self.embed_head = nn.Sequential(
            nn.Flatten(),                     # → (batch, 256)
            nn.Linear(256, embed_dim),
            nn.LayerNorm(embed_dim),
            nn.ReLU(inplace=True),
            nn.Dropout(0.3),
        )

        self.classifier = nn.Linear(embed_dim, 1)

    def forward(self, x: torch.Tensor,
                return_embedding: bool = False) -> torch.Tensor:
        feat = self.encoder(x)
        feat = self.gap(feat)
        emb  = self.embed_head(feat)

        if return_embedding:
            return emb                              # (batch, embed_dim)
        return self.classifier(emb).squeeze(1)     # (batch,)

"""# Load splits"""

id_train = np.load(os.path.join(SPLIT_DIR, "ids_train.npy"), allow_pickle=True)
id_val   = np.load(os.path.join(SPLIT_DIR, "ids_val.npy"),   allow_pickle=True)
id_test  = np.load(os.path.join(SPLIT_DIR, "ids_test.npy"),  allow_pickle=True)

y_train  = np.load(os.path.join(SPLIT_DIR, "y_train.npy"))
y_val    = np.load(os.path.join(SPLIT_DIR, "y_val.npy"))
y_test   = np.load(os.path.join(SPLIT_DIR, "y_test.npy"))

# Build label lookup
labels = {}
for ids_arr, ys in [(id_train, y_train), (id_val, y_val), (id_test, y_test)]:
    for cid, y in zip(ids_arr, ys):
        labels[str(cid)] = int(y)

print(f"Cases — train:{len(id_train)}  val:{len(id_val)}  test:{len(id_test)}")
print(f"Patches per epoch (train): {len(id_train) * PATCHES_PER_CASE}")
print(f"Input mode: {'CoLIAGe (28ch)' if USE_COLIAGE else 'Raw CT (1ch)'}")

# ─────────────────────────────────────────────────────────────────────────────
# Z-SCORE NORMALIZATION — compute mean/std from training images ONLY
# Applied per-volume: each patch is normalized using the global training stats.
# This follows the same discipline as StandardScaler in the radiomic branch:
#   fit on training data only → transform all splits consistently.
# ─────────────────────────────────────────────────────────────────────────────
if APPLY_ZSCORE and not USE_COLIAGE:
    if ZSCORE_STATS_FILE is not None and os.path.exists(ZSCORE_STATS_FILE):
        stats      = np.load(ZSCORE_STATS_FILE)
        CT_MEAN    = float(stats["mean"])
        CT_STD     = float(stats["std"])
        print(f"\nZ-score stats loaded from {ZSCORE_STATS_FILE}")
        print(f"  CT_MEAN = {CT_MEAN:.4f} HU   CT_STD = {CT_STD:.4f} HU")
    else:
        print(f"\nComputing Z-score statistics from {len(id_train)} training images...")
        pixel_sum   = 0.0
        pixel_sum_sq = 0.0
        pixel_count  = 0

        for cid in id_train:
            img_path = os.path.join(IMAGE_DIR, f"{cid}_image.npy")
            if not os.path.exists(img_path):
                continue
            img = np.load(img_path).astype(np.float32)
            pixel_sum    += img.sum()
            pixel_sum_sq += (img ** 2).sum()
            pixel_count  += img.size

        CT_MEAN = pixel_sum / pixel_count
        CT_VAR  = (pixel_sum_sq / pixel_count) - (CT_MEAN ** 2)
        CT_STD  = float(np.sqrt(max(CT_VAR, 1e-8)))

        np.savez(ZSCORE_STATS_FILE, mean=CT_MEAN, std=CT_STD)
        print(f"  CT_MEAN = {CT_MEAN:.4f} HU   CT_STD = {CT_STD:.4f} HU")
        print(f"  Computed over {pixel_count:,} voxels from {len(id_train)} cases")
        print(f"  Saved to {ZSCORE_STATS_FILE}")
else:
    CT_MEAN = 0.0
    CT_STD  = 1.0
    if not APPLY_ZSCORE:
        print("\nZ-score normalization disabled (APPLY_ZSCORE=False).")
    else:
        print("\nZ-score normalization skipped for CoLIAGe input mode.")

"""# DataLoaders"""

_common = dict(
    image_dir        = IMAGE_DIR,
    mask_dir         = MASK_DIR,
    patch_size       = PATCH_SIZE,
    use_coliage      = USE_COLIAGE,
    coliage_dir      = COLIAGE_DIR,
    ct_mean          = CT_MEAN,    # training-set Z-score mean (0.0 if disabled)
    ct_std           = CT_STD,     # training-set Z-score std  (1.0 if disabled)
)

train_dataset = PatchDataset(
    case_ids         = list(id_train),
    labels           = labels,
    patches_per_case = PATCHES_PER_CASE,
    augment          = True,
    **_common,
)
val_dataset = PatchDataset(
    case_ids         = list(id_val),
    labels           = labels,
    patches_per_case = 1,
    augment          = False,
    **_common,
)
test_dataset = PatchDataset(
    case_ids         = list(id_test),
    labels           = labels,
    patches_per_case = 1,
    augment          = False,
    **_common,
)

def collate_fn(batch):
    """Custom collate that keeps case_id strings separate from tensors."""
    patches  = torch.stack([b[0] for b in batch])
    labels_t = torch.stack([b[1] for b in batch])
    case_ids = [b[2] for b in batch]
    return patches, labels_t, case_ids

train_loader = DataLoader(
    train_dataset, batch_size=BATCH_SIZE, shuffle=True,
    num_workers=NUM_WORKERS, pin_memory=True, collate_fn=collate_fn,
)
val_loader = DataLoader(
    val_dataset, batch_size=BATCH_SIZE, shuffle=False,
    num_workers=NUM_WORKERS, collate_fn=collate_fn,
)
test_loader = DataLoader(
    test_dataset, batch_size=BATCH_SIZE, shuffle=False,
    num_workers=NUM_WORKERS, collate_fn=collate_fn,
)

"""# Model, optimizer, loss"""

# @title
in_channels = 28 if USE_COLIAGE else 1
model       = Simple3DCNN(in_channels=in_channels, embed_dim=EMBED_DIM).to(device)
optimizer   = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler   = torch.optim.lr_scheduler.LinearLR(
    optimizer, start_factor=1.0, end_factor=0.1, total_iters=N_EPOCHS
)

#n_neg, n_pos  = int((y_train == 0).sum()), int((y_train == 1).sum())
#pos_weight    = torch.tensor([n_neg / n_pos], dtype=torch.float32).to(device)
#criterion     = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

n_neg, n_pos = int((y_train == 0).sum()), int((y_train == 1).sum())
pos_weight = torch.tensor([n_neg / n_pos], dtype=torch.float32).to(device)
# With your numbers: 1092 / 473 ≈ 2.31
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

total_params  = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\nModel parameters: {total_params:,}")
print(f"Positive class weight: {pos_weight.item():.3f}  "
      f"(non-PDAC={n_neg}, PDAC={n_pos})\n")

"""# Training loop"""

best_val_auc = 0.0
no_improve   = 0
history      = {"train_loss": [], "val_auc": []}

print("── Training " + "─" * 50)

for epoch in range(N_EPOCHS):

    # ── Train ──────────────────────────────────────────────────────────────
    model.train()
    epoch_loss = 0.0

    for X_batch, y_batch, _ in train_loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)
        optimizer.zero_grad()
        logits = model(X_batch)
        loss   = criterion(logits, y_batch)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    scheduler.step()
    avg_loss = epoch_loss / len(train_loader)

    # ── Validate ───────────────────────────────────────────────────────────
    model.eval()
    all_probs, all_labels_val = [], []

    with torch.no_grad():
        for X_batch, y_batch, _ in val_loader:
            logits = model(X_batch.to(device))
            probs  = torch.sigmoid(logits).cpu().numpy()
            all_probs.extend(probs.tolist())
            all_labels_val.extend(y_batch.numpy().tolist())

    val_auc = roc_auc_score(all_labels_val, all_probs)
    history["train_loss"].append(avg_loss)
    history["val_auc"].append(val_auc)

    flag = ""
    if val_auc > best_val_auc + 1e-4:
        best_val_auc = val_auc
        torch.save(model.state_dict(),
                   os.path.join(OUTPUT_DIR, "best_cnn.pt"))
        no_improve = 0
        flag = "  ✓ saved"
    else:
        no_improve += 1

    print(f"Epoch {epoch+1:02d}/{N_EPOCHS} | "
          f"Loss: {avg_loss:.4f} | Val AUC: {val_auc:.4f}{flag}")

    if no_improve >= PATIENCE:
        print(f"\nEarly stopping at epoch {epoch+1}.")
        break

# ── Training curves ───────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(history["train_loss"], color="steelblue")
axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("BCE Loss")
axes[0].set_title("Training Loss")

axes[1].plot(history["val_auc"], color="tomato")
axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("ROC-AUC")
axes[1].set_title("Validation AUC")

plt.tight_layout()
plt.show()

plt.savefig(os.path.join(OUTPUT_DIR, "cnn_training_curves_MONAI.png"), dpi=150)
plt.close()
print(f"Training curves saved.")

"""# Extract embeddings for all splits (one centroid patch per case)"""

print("── Extracting patient-level embeddings ──")
print("   Train : average of all patch embeddings per case")
print("   Val   : single centroid patch embedding per case")
print("   Test  : single centroid patch embedding per case\n")

model.load_state_dict(torch.load(os.path.join(OUTPUT_DIR, "best_cnn.pt"), map_location=device))
model.eval()

# @title
def extract_train_embeddings(case_ids_ordered: np.ndarray) -> np.ndarray:
    """
    Training split: extract embeddings from ALL patches per case,
    then average them into one patient-level vector.

    During training, PATCHES_PER_CASE=4 random patches were sampled
    per case per epoch. Here we re-sample all 4 patches deterministically
    (same seed per case) and average their embeddings, giving a richer
    patient-level representation than a single centroid patch.
    """
    # Build a dedicated loader: patches_per_case=PATCHES_PER_CASE,
    # augment=False (no flips during embedding extraction),
    # shuffle=False (preserve case grouping for averaging)
    train_emb_dataset = PatchDataset(
        case_ids         = list(case_ids_ordered),
        labels           = labels,
        image_dir        = IMAGE_DIR,
        mask_dir         = MASK_DIR,
        patch_size       = PATCH_SIZE,
        patches_per_case = PATCHES_PER_CASE,   # all patches, not just centroid
        use_coliage      = USE_COLIAGE,
        coliage_dir      = COLIAGE_DIR,
        augment          = False,               # no augmentation during extraction
        ct_mean          = CT_MEAN,            # same stats used during training
        ct_std           = CT_STD,
    )
    train_emb_loader = DataLoader(
        train_emb_dataset,
        batch_size  = BATCH_SIZE,
        shuffle     = False,    # must be False — order matters for averaging
        num_workers = NUM_WORKERS,
        collate_fn  = collate_fn,
    )

    # Collect embeddings per case_id
    emb_accumulator = {}   # case_id → list of embedding arrays

    with torch.no_grad():
        for X_batch, _, case_ids_batch in train_emb_loader:
            embs = model(X_batch.to(device), return_embedding=True)
            embs = embs.cpu().numpy()
            for cid, emb in zip(case_ids_batch, embs):
                cid = str(cid)
                if cid not in emb_accumulator:
                    emb_accumulator[cid] = []
                emb_accumulator[cid].append(emb)

    # Average patch embeddings → one vector per case
    emb_matrix = np.stack([
        np.mean(emb_accumulator[str(cid)], axis=0)
        for cid in case_ids_ordered
    ])
    print(f"  train: {emb_matrix.shape}  "
          f"(averaged {PATCHES_PER_CASE} patches × {len(case_ids_ordered)} cases)")
    return emb_matrix.astype(np.float32)

# @title
def extract_centroid_embeddings(loader,
                                 case_ids_ordered: np.ndarray,
                                 split_name: str) -> np.ndarray:
    """
    Val / test splits: extract ONE centroid patch embedding per case.
    The centroid patch is deterministic (same center every time),
    so this gives a stable, reproducible patient-level representation.
    """
    emb_dict = {}

    with torch.no_grad():
        for X_batch, _, case_ids_batch in loader:
            embs = model(X_batch.to(device), return_embedding=True)
            embs = embs.cpu().numpy()
            for cid, emb in zip(case_ids_batch, embs):
                emb_dict[str(cid)] = emb

    emb_matrix = np.stack([emb_dict[str(cid)] for cid in case_ids_ordered])
    print(f"  {split_name}: {emb_matrix.shape}  (1 centroid patch per case)")
    return emb_matrix.astype(np.float32)

# ── Extract patient-level embeddings for all three splits ─────────────────────
deep_train = extract_train_embeddings(id_train)
deep_val   = extract_centroid_embeddings(val_loader,  id_val,  "val")
deep_test  = extract_centroid_embeddings(test_loader, id_test, "test")

np.save(os.path.join(OUTPUT_DIR, "deep_embeddings_train.npy"), deep_train)
np.save(os.path.join(OUTPUT_DIR, "deep_embeddings_val.npy"),   deep_val)
np.save(os.path.join(OUTPUT_DIR, "deep_embeddings_test.npy"),  deep_test)

print(f"\nSaved deep embeddings:")
print(f"  deep_embeddings_train.npy → {deep_train.shape}")
print(f"  deep_embeddings_val.npy   → {deep_val.shape}")
print(f"  deep_embeddings_test.npy  → {deep_test.shape}")
print(f"  best_cnn.pt")
print("\nStep 6 complete. Run step7_fusion.py next.")

"""# **6b — CNN Branch Evaluation**"""

# @title
# -*- coding: utf-8 -*-
"""STEP 6b — CNN Branch Evaluation
====================================
Evaluates the quality of the CNN embeddings produced by Step 6
by training classical classifiers on top of them — exactly mirroring
Step 5b (radiomic branch evaluation) so results are directly comparable.

Input  : deep_embeddings_train/val/test.npy   (from step6_outputs)
         y_train/val/test.npy                 (from step2_outputs)

Output (saved to step6b_outputs):
  results_val.csv / results_test.csv
  comparison_val.png / comparison_test.png
  brier_val.png / brier_test.png
  roc_curves.png
  pr_curves.png
  confusion_matrices.png
  calibration.png
  best_model.pkl
  all_models.pkl
  best_hparams.pkl

Why this step exists
--------------------
The Step 6 training loop only measures the CNN's own linear head (one
Linear layer on top of the 128-D embedding).  That is a weak classifier
deliberately kept simple so the embedding head learns general features
rather than overfitting to the classification task.

Step 6b asks: how much PDAC signal do the embeddings contain when you
give them a proper classifier?  The answer becomes the CNN-only baseline
in your thesis ablation table:

  Radiomic only  (Step 5b best model)  → AUC ~ 0.57
  CNN only       (Step 6b best model)  → AUC ~ ?
  Fusion         (Step 7)              → AUC ~ ?

Without Step 6b you cannot prove the fusion is better than either
branch alone.

Metrics reported
----------------
  ROC-AUC, Average Precision, Brier Score,
  Accuracy, Sensitivity, Specificity, F1, MCC
"""

# @title
# ── Imports ───────────────────────────────────────────────────────────────────
import os, warnings
import numpy as np
import pandas as pd
import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from sklearn.linear_model    import LogisticRegression
from sklearn.svm             import SVC
from sklearn.ensemble        import RandomForestClassifier
from sklearn.calibration     import calibration_curve
from sklearn.model_selection import ParameterGrid
from sklearn.metrics         import (
    roc_auc_score, average_precision_score, brier_score_loss,
    accuracy_score, confusion_matrix, f1_score, matthews_corrcoef,
    roc_curve, precision_recall_curve,
)
from xgboost import XGBClassifier

# ── CONFIG ────────────────────────────────────────────────────────────────────
# Update these paths to match your environment
STEP2_DIR   = "/content/drive/MyDrive/metrics_batch1/step2_outputs"
STEP6_DIR   = "/content/drive/MyDrive/metrics_batch1/step6_outputs"
OUTPUT_DIR  = "/content/drive/MyDrive/metrics_batch1/step6b_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

RANDOM_STATE = 42
DPI          = 150

PALETTE = {
    "LogReg" : "#2196F3",
    "SVM"    : "#FF9800",
    "RF"     : "#4CAF50",
    "XGB"    : "#E91E63",
}

# ── Load embeddings and labels ────────────────────────────────────────────────
X_train = np.load(os.path.join(STEP6_DIR, "deep_embeddings_train.npy"))
X_val = np.load(os.path.join(STEP6_DIR, "deep_embeddings_val.npy"))
X_test = np.load(os.path.join(STEP6_DIR, "deep_embeddings_test.npy"))

y_train = np.load(os.path.join(STEP2_DIR, "y_train.npy"))
y_val = np.load(os.path.join(STEP2_DIR, "y_val.npy"))
y_test = np.load(os.path.join(STEP2_DIR, "y_test.npy"))

# Feature names — embeddings have no semantic names, just indices
feat_names = [f"emb_{i}" for i in range(X_train.shape[1])]

n_pos = int(y_train.sum())
n_neg = int((y_train == 0).sum())
spw   = n_neg / n_pos

print(f"Embeddings — train:{X_train.shape}  val:{X_val.shape}  test:{X_test.shape}")
print(f"PDAC       — train:{n_pos}  non-PDAC:{n_neg}")
print(f"Embedding dimension: {X_train.shape[1]}\n")

"""## Helpers  (identical to Step 5b)"""

def compute_metrics(y_true, y_prob, threshold=0.5):
    y_pred = (y_prob >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    sens = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    spec = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    return {
        "ROC-AUC"    : round(roc_auc_score(y_true, y_prob), 4),
        "Avg-Prec"   : round(average_precision_score(y_true, y_prob), 4),
        "Brier"      : round(brier_score_loss(y_true, y_prob), 4),
        "Accuracy"   : round(accuracy_score(y_true, y_pred), 4),
        "Sensitivity": round(sens, 4),
        "Specificity": round(spec, 4),
        "F1"         : round(f1_score(y_true, y_pred, zero_division=0), 4),
        "MCC"        : round(matthews_corrcoef(y_true, y_pred), 4),
        "TP": tp, "TN": tn, "FP": fp, "FN": fn,
        "threshold"  : threshold,
    }

def find_best_threshold(y_true, y_prob):
    """Youden's J: maximises sensitivity + specificity on the given split."""
    fpr, tpr, thresholds = roc_curve(y_true, y_prob)
    j = tpr - fpr
    return float(thresholds[np.argmax(j)])

"""## Model grids  (identical to Step 5b)"""

MODEL_GRIDS = {
    "LogReg": {
        "class": LogisticRegression,
        "fixed": {"solver": "lbfgs", "max_iter": 1000,
                  "class_weight": "balanced", "random_state": RANDOM_STATE},
        "grid" : {"C": [0.01, 0.1, 1.0, 10.0]},
    },
    "SVM": {
        "class": SVC,
        "fixed": {"kernel": "rbf", "probability": True,
                  "class_weight": "balanced", "random_state": RANDOM_STATE},
        "grid" : {"C": [0.1, 1.0, 10.0], "gamma": ["scale", "auto"]},
    },
    "RF": {
        "class": RandomForestClassifier,
        "fixed": {"n_estimators": 500, "class_weight": "balanced_subsample",
                  "random_state": RANDOM_STATE, "n_jobs": -1},
        "grid" : {"max_depth": [None, 5, 10],
                  "min_samples_leaf": [1, 2, 4]},
    },
    "XGB": {
        "class": XGBClassifier,
        "fixed": {"n_estimators": 300, "eval_metric": "logloss",
                  "scale_pos_weight": spw,
                  "random_state": RANDOM_STATE, "verbosity": 0, "n_jobs": -1},
        "grid" : {"max_depth": [3, 5, 7],
                  "learning_rate": [0.01, 0.05, 0.1],
                  "subsample": [0.8, 1.0]},
    },
}

"""## Training — grid search on val AUC, test set never touched"""

#CNN Branch — classifier grid search on val AUC
best_models     = {}
best_hparams    = {}
val_probs       = {}
test_probs      = {}
best_thresholds = {}

for name, cfg in MODEL_GRIDS.items():
    print(f"\n── {name} ──────────────────────────────────────")
    best_auc, best_model, best_param = -1, None, None

    for params in ParameterGrid(cfg["grid"]):
        clf = cfg["class"](**{**cfg["fixed"], **params})
        clf.fit(X_train, y_train)
        prob_v = clf.predict_proba(X_val)[:, 1]
        auc_v  = roc_auc_score(y_val, prob_v)
        if auc_v > best_auc:
            best_auc, best_model, best_param = auc_v, clf, params

    print(f"  Best params : {best_param}")
    print(f"  Val AUC     : {best_auc:.4f}")

    best_models[name]     = best_model
    best_hparams[name]    = best_param
    val_probs[name]       = best_model.predict_proba(X_val)[:, 1]
    test_probs[name]      = best_model.predict_proba(X_test)[:, 1]
    best_thresholds[name] = find_best_threshold(y_val, val_probs[name])

print()

"""## Metrics"""

records_val, records_test = [], []
for name in best_models:
    thr = best_thresholds[name]
    records_val.append( {"Model": name,
                          **compute_metrics(y_val,  val_probs[name],  thr)})
    records_test.append({"Model": name,
                          **compute_metrics(y_test, test_probs[name], thr)})

df_val  = pd.DataFrame(records_val).set_index("Model")
df_test = pd.DataFrame(records_test).set_index("Model")
best_name = df_val["ROC-AUC"].idxmax()

METRIC_DISPLAY = ["ROC-AUC","Avg-Prec","Brier","Accuracy",
                  "Sensitivity","Specificity","F1","MCC"]

print("=" * 65)
print("VALIDATION METRICS  (CNN embeddings)")
print("=" * 65)
print(df_val[METRIC_DISPLAY].to_string())
print(f"\n  ★ Best model by val AUC: {best_name}\n")

print("=" * 65)
print("TEST METRICS  (CNN embeddings)")
print("=" * 65)
print(df_test[METRIC_DISPLAY].to_string())

df_val.to_csv( os.path.join(OUTPUT_DIR, "results_val.csv"))
df_test.to_csv(os.path.join(OUTPUT_DIR, "results_test.csv"))

"""## Plots"""

model_names = list(best_models.keys())

# ── ROC curves ────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for ax, (probs, y_true, title) in zip(axes, [
    (val_probs,  y_val,  "Validation"),
    (test_probs, y_test, "Test"),
]):
    for name, prob in probs.items():
        fpr, tpr, _ = roc_curve(y_true, prob)
        ax.plot(fpr, tpr, label=f"{name}  AUC={roc_auc_score(y_true, prob):.3f}",
                color=PALETTE[name], lw=2)
    ax.plot([0,1],[0,1],"k--",lw=1)
    ax.set_xlabel("False Positive Rate"); ax.set_ylabel("True Positive Rate")
    ax.set_title(f"ROC Curves — {title}  (CNN embeddings)",
                 fontweight="bold")
    ax.legend(fontsize=9); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "roc_curves.png"), dpi=DPI)
plt.close()

"""### ── Metric bar charts"""

METRIC_COLS = ["ROC-AUC","Avg-Prec","Accuracy","Sensitivity",
               "Specificity","F1","MCC"]
for df, split in [(df_val,"val"),(df_test,"test")]:
    fig, axes = plt.subplots(1, len(METRIC_COLS), figsize=(18, 4))
    for ax, metric in zip(axes, METRIC_COLS):
        vals   = df[metric]
        colors = [PALETTE[m] for m in vals.index]
        bars   = ax.bar(vals.index, vals.values, color=colors, edgecolor="white")
        ax.set_title(metric, fontsize=10, fontweight="bold")
        ax.set_ylim(0, 1.08); ax.grid(axis="y", alpha=0.3)
        ax.set_xticklabels(vals.index, fontsize=8, rotation=20)
        for bar, v in zip(bars, vals.values):
            ax.text(bar.get_x()+bar.get_width()/2, v+0.01,
                    f"{v:.3f}", ha="center", va="bottom", fontsize=7)
    fig.suptitle(f"CNN Branch — {split.capitalize()} Set",
                 fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, f"comparison_{split}.png"),
                dpi=DPI, bbox_inches="tight")
    plt.close()

    # Brier separately (lower = better, opposite direction)
    fig2, ax2 = plt.subplots(figsize=(4, 4))
    bv = df["Brier"]
    bars2 = ax2.bar(bv.index, bv.values,
                    color=[PALETTE[m] for m in bv.index], edgecolor="white")
    ax2.set_title("Brier Score (↓ better)", fontweight="bold")
    ax2.set_ylim(0, max(bv.values)*1.3+0.05); ax2.grid(axis="y", alpha=0.3)
    for bar, v in zip(bars2, bv.values):
        ax2.text(bar.get_x()+bar.get_width()/2, v+0.002,
                 f"{v:.3f}", ha="center", va="bottom", fontsize=9)
    fig2.tight_layout()
    fig2.savefig(os.path.join(OUTPUT_DIR, f"brier_{split}.png"), dpi=DPI)
    plt.close(fig2)

"""### ── Confusion matrices"""

fig, axes = plt.subplots(2, 4, figsize=(16, 7))
for col, name in enumerate(model_names):
    for row, (probs, y_true, split) in enumerate([
        (val_probs,  y_val,  "Val"),
        (test_probs, y_test, "Test"),
    ]):
        thr  = best_thresholds[name]
        pred = (probs[name] >= thr).astype(int)
        cm   = confusion_matrix(y_true, pred, labels=[0, 1])
        ax   = axes[row][col]
        ax.imshow(cm, cmap="Blues")
        for i in range(2):
            for j in range(2):
                ax.text(j, i, str(cm[i,j]), ha="center", va="center",
                        fontsize=14, fontweight="bold",
                        color="white" if cm[i,j] > cm.max()/2 else "black")
        ax.set_xticks([0,1]); ax.set_xticklabels(["non-PDAC","PDAC"])
        ax.set_yticks([0,1]); ax.set_yticklabels(["non-PDAC","PDAC"])
        ax.set_xlabel("Predicted"); ax.set_ylabel("Actual")
        ax.set_title(f"{name} — {split}", fontweight="bold",
                     color=PALETTE[name])
fig.suptitle("Confusion Matrices — CNN Branch  "
             "(top: Validation | bottom: Test)", fontweight="bold")
plt.tight_layout()
plt.show()

plt.savefig(os.path.join(OUTPUT_DIR, "confusion_matrices.png"),
            dpi=DPI, bbox_inches="tight")
plt.close()

"""### ── Calibration"""

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for ax, (probs, y_true, title) in zip(axes, [
    (val_probs,  y_val,  "Validation"),
    (test_probs, y_test, "Test"),
]):
    ax.plot([0,1],[0,1],"k--",lw=1,label="Perfect calibration")
    for name, prob in probs.items():
        frac_pos, mean_pred = calibration_curve(y_true, prob,
                                                n_bins=8, strategy="uniform")
        brier = brier_score_loss(y_true, prob)
        ax.plot(mean_pred, frac_pos, "o-", color=PALETTE[name], lw=2,
                label=f"{name}  Brier={brier:.3f}")
    ax.set_xlabel("Mean predicted probability")
    ax.set_ylabel("Fraction of positives (PDAC)")
    ax.set_title(f"Calibration — {title}  (CNN embeddings)", fontweight="bold")
    ax.legend(fontsize=9); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "calibration.png"), dpi=DPI)
plt.close()

# ── Precision-Recall curves ───────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for ax, (probs, y_true, title) in zip(axes, [
    (val_probs,  y_val,  "Validation"),
    (test_probs, y_test, "Test"),
]):
    ax.axhline(y_true.mean(), color="gray", linestyle="--", lw=1,
               label=f"Baseline (prevalence={y_true.mean():.2f})")
    for name, prob in probs.items():
        prec, rec, _ = precision_recall_curve(y_true, prob)
        ap = average_precision_score(y_true, prob)
        ax.plot(rec, prec, color=PALETTE[name], lw=2,
                label=f"{name}  AP={ap:.3f}")
    ax.set_xlabel("Recall (Sensitivity)"); ax.set_ylabel("Precision")
    ax.set_title(f"Precision-Recall — {title}  (CNN embeddings)",
                 fontweight="bold")
    ax.legend(fontsize=9); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "pr_curves.png"), dpi=DPI)
plt.close()

print("Saved: roc_curves.png  comparison_val/test.png  brier_val/test.png")
print("       confusion_matrices.png  calibration.png  pr_curves.png")


# ─────────────────────────────────────────────────────────────────────────────
# Save models
# ─────────────────────────────────────────────────────────────────────────────
joblib.dump(best_models[best_name], os.path.join(OUTPUT_DIR, "best_model.pkl"))
joblib.dump(best_models,            os.path.join(OUTPUT_DIR, "all_models.pkl"))
joblib.dump(best_hparams,           os.path.join(OUTPUT_DIR, "best_hparams.pkl"))

"""## Final comparison table"""

print(f"\n{'='*65}")
print("FINAL COMPARISON SUMMARY — CNN Branch")
print(f"{'='*65}")
print(f"{'Model':<10} {'Val AUC':>8} {'Test AUC':>9} {'Val Sens':>9} "
      f"{'Test Sens':>10} {'Val Spec':>9} {'Test Spec':>10} "
      f"{'Val F1':>8} {'Test F1':>8}")
print("-" * 85)
for name in model_names:
    v = df_val.loc[name]
    t = df_test.loc[name]
    star = " ★" if name == best_name else ""
    print(f"{name:<10} {v['ROC-AUC']:>8.4f} {t['ROC-AUC']:>9.4f} "
          f"{v['Sensitivity']:>9.4f} {t['Sensitivity']:>10.4f} "
          f"{v['Specificity']:>9.4f} {t['Specificity']:>10.4f} "
          f"{v['F1']:>8.4f} {t['F1']:>8.4f}{star}")

print(f"\n  ★ Best CNN model : {best_name}  "
      f"(val AUC={df_val.loc[best_name,'ROC-AUC']:.4f}, "
      f"test AUC={df_test.loc[best_name,'ROC-AUC']:.4f})")

print(f"\nAll outputs saved to: {OUTPUT_DIR}")
print("Run step7_fusion.py next.")