# -*- coding: utf-8 -*-
"""STEP1_cudalomi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159zrKCgiFFUDOrY7CtddFPDKZVX4EFc3

# **STEP 1 — Spatial Aggregation of CoLIAGe Volumes**

Input  : {case_id}_coliage.npy  → (128, 128, 128, 28)  per case

Output :
*       master_X.npy           → (N_cases, 112)
        master_y.npy           → (N_cases,)
        master_ids.npy         → (N_cases,)
        master_radiomics.csv   → human-readable version

Aggregation:
*           for each of the 26 CoLIAGe channels, compute
            mean / std / Q25 / Q75 within the ROI voxels
            → 26 × 4 = 112 features per case.

**CoLIAGe already restricts computation to the ROI internally,
so non-ROI voxels are 0 or NaN**. We reconstruct the ROI from
the output itself and verify it once against the saved mask.

CONFIGURE the paths in the CONFIG block below before running.

# aaaa
"""

import argparse
import os
import json
import time
from typing import Optional, Tuple

import numpy as np
import pandas as pd

parser = argparse.ArgumentParser()
parser.add_argument("--coliage_dir", required=True,
                    help="Directory containing *_tensor_128_27ch.npy files for this batch")
parser.add_argument("--output_dir", required=True,
                    help="Where to save this batch's partial master_X.npy")
parser.add_argument("--batch_name", required=True,
                    help="Identifier for this batch, e.g. batch_01")
parser.add_argument("--mask_dir", required=False, default=None,
                    help="Directory containing {case_id}_mask.npy files, "
                         "used only for optional ROI verification")
args = parser.parse_args()

COLIAGE_DIR = args.coliage_dir
OUTPUT_DIR  = args.output_dir
BATCH_NAME  = args.batch_name
MASK_DIR    = args.mask_dir

os.makedirs(OUTPUT_DIR, exist_ok=True)

N_CHANNELS    = 26                    # texture channels used for aggregation - (excludes channel 0 = CT, channel 27 = label):
CT_CHANNEL_IDX    = 0                 # index of the raw CT channel (not aggregated)
LABEL_CHANNEL_IDX = 27                # index of the binary PDAC label channel
VERIFY_MASK   = True                  # set False after first successful run

STATS        = ["mean", "std", "q25", "q75"]
FEATURE_NAMES = [
    f"haralick_{c+1}_{s}"
    for c in range(N_CHANNELS)
    for s in STATS
]   # 104 names: haralick_1_mean, haralick_1_std, ..., haralick_26_q75

"""# Aggregation function"""

def aggregate_coliage(coliage_path: str,
                      mask_path: Optional[str] = None,
                      verify: bool = False,
                      max_retries: int = 3,
                      retry_delay: float = 3.0) -> Tuple[np.ndarray, int]:
    """
    Load one CoLIAGe tensor, extract the PDAC label from the label
    channel, and return a 104-dim feature vector aggregated over the
    26 texture channels only (CT and label channels excluded).

    Retries on Drive mount disconnects (Errno 107) since those are
    transient connection drops, not file corruption — retrying after
    a short pause almost always succeeds once the mount recovers.

    Tensor channel layout (28 channels total):
        channel 0       → normalized CT (excluded from aggregation)
        channels 1-26   → 26 Haralick texture channels (aggregated)
        channel 27      → binary PDAC label, constant across all voxels

    Parameters
    ----------
    coliage_path : path to (128,128,128,28) .npy file
    mask_path    : path to (128,128,128) binary .npy file (optional)
                   used only for ROI reconstruction verification
    verify       : if True and mask_path given, prints ROI overlap stats
    max_retries  : number of attempts before giving up on this file
    retry_delay  : seconds to wait between retries

    Returns
    -------
    (feature_vector, label)
        feature_vector : np.ndarray of shape (104,)  dtype float32
        label          : int, 0 or 1, read directly from the tensor
    """
    import time

    last_error = None
    for attempt in range(max_retries):
        try:
            tensor = np.load(coliage_path).astype(np.float32)   # (H, W, D, 28)
            break   # success — exit retry loop
        except (OSError, ValueError) as e:
            last_error = e
            if attempt < max_retries - 1:
                print(f"    Read failed (attempt {attempt+1}/{max_retries}): "
                      f"{type(e).__name__}: {e}")
                print(f"    Likely a Drive mount hiccup — retrying in "
                      f"{retry_delay}s...")
                time.sleep(retry_delay)
                continue
            else:
                raise RuntimeError(
                    f"Failed to load {coliage_path} after {max_retries} attempts. "
                    f"Last error: {last_error}\n"
                    f"If this persists, remount Drive manually:\n"
                    f"  from google.colab import drive\n"
                    f"  drive.flush_and_unmount()\n"
                    f"  import time; time.sleep(5)\n"
                    f"  drive.mount('/content/drive', force_remount=True)"
                ) from last_error

    assert tensor.ndim == 4, \
        f"Expected 4D array, got shape {tensor.shape}"
    assert tensor.shape[3] == N_CHANNELS + 2, \
        f"Expected {N_CHANNELS + 2} total channels " \
        f"(1 CT + {N_CHANNELS} texture + 1 label), got {tensor.shape[3]}"

    # ── Extract label from the label channel ──────────────────────────────
    # This channel is constant across all voxels (all 0s or all 1s),
    # so any single voxel value is the case label.
    label_channel = tensor[..., LABEL_CHANNEL_IDX]
    unique_label_vals = np.unique(label_channel)

    assert len(unique_label_vals) == 1, \
        f"Label channel is not constant! Found values: {unique_label_vals}. " \
        f"This suggests the tensor structure doesn't match expectations."

    label = int(round(float(unique_label_vals[0])))
    assert label in (0, 1), \
        f"Label channel value {label} is not 0 or 1 — check LABEL_CHANNEL_IDX."

    # ── Isolate only the texture channels for aggregation ─────────────────
    texture_channels = tensor[..., 1:1 + N_CHANNELS]   # channels 1-26

    # ── Reconstruct ROI from texture channels (CoLIAGe restricts to ROI) ──
    roi = np.any(np.isfinite(texture_channels) & (texture_channels != 0.0), axis=-1)
    n_roi = int(roi.sum())

    assert n_roi > 0, \
        f"No valid ROI voxels found in {coliage_path}. " \
        f"Check that CoLIAGe was run with a non-empty mask."

    # ── Optional: verify against saved mask ──────────────────────────────
    # NOTE: saved masks are stored as (D, H, W) while the CoLIAGe tensor's
    # spatial axes are (H, W, D). Confirmed via diagnose_alignment.py on
    # 10 cases (10/10, IoU 0.00-0.08 -> 0.975-0.999), so masks are
    # transposed with (2, 0, 1) before comparison.
    MASK_AXIS_TRANSPOSE = (2, 0, 1)

    if verify and mask_path is not None:
        if os.path.exists(mask_path):
            saved_mask = np.load(mask_path).astype(bool)
            saved_mask = np.transpose(saved_mask, MASK_AXIS_TRANSPOSE)
            overlap    = np.logical_and(roi, saved_mask).sum()
            union      = np.logical_or(roi, saved_mask).sum()
            iou        = overlap / union if union > 0 else 0.0
            print(f"    Mask verify | CoLIAGe ROI voxels: {n_roi:,} | "
                  f"Saved mask voxels: {int(saved_mask.sum()):,} | "
                  f"IoU: {iou:.3f}")
            if iou < 0.80:
                print(f"    WARNING: Low IoU ({iou:.3f}) — check mask/coliage alignment!")
        else:
            print(f"    Mask verify SKIPPED — file not found: {mask_path}")

    # ── Aggregate each texture channel ──────────────────────────────────────
    feature_vector = np.zeros(N_CHANNELS * len(STATS), dtype=np.float32)

    for c in range(N_CHANNELS):
        feat_map = texture_channels[..., c]   # (H, W, D)
        roi_vals = feat_map[roi]              # (n_roi,)  — ROI voxels only

        # Drop any NaNs/Infs that CoLIAGe may produce at ROI boundary
        roi_vals = roi_vals[np.isfinite(roi_vals)]

        if len(roi_vals) == 0:
            # Fallback: channel is entirely NaN inside ROI
            stats = [0.0, 0.0, 0.0, 0.0]
            print(f"    WARNING: channel {c+1} has no finite values inside ROI!")
        else:
            stats = [
                float(roi_vals.mean()),
                float(roi_vals.std()),
                float(np.percentile(roi_vals, 25)),
                float(np.percentile(roi_vals, 75)),
            ]

        base = c * len(STATS)
        feature_vector[base : base + len(STATS)] = stats

    return feature_vector, label   # (104,), int

"""# Main loop — iterate over all CoLIAGe files"""

FILENAME_SUFFIX = "_tensor_128_27ch.npy"
coliage_files = sorted([
    f for f in os.listdir(COLIAGE_DIR)
    if f.endswith(FILENAME_SUFFIX)
])

if len(coliage_files) == 0:
    raise FileNotFoundError(
        f"No *{FILENAME_SUFFIX} files found in {COLIAGE_DIR}. "
        f"Check your COLIAGE_DIR path and FILENAME_SUFFIX."
    )

print(f"Found {len(coliage_files)} CoLIAGe files in '{COLIAGE_DIR}'.")
print(f"Output feature dimension: {N_CHANNELS} texture channels × "
      f"{len(STATS)} stats = {N_CHANNELS * len(STATS)}")
print(f"Label is read directly from channel {LABEL_CHANNEL_IDX} of each tensor.\n")

records = []
failed_cases = []
label_mismatches = []

for i, filename in enumerate(coliage_files):
    case_id      = filename.replace(FILENAME_SUFFIX, "")
    coliage_path = os.path.join(COLIAGE_DIR, filename)
    mask_path    = os.path.join(MASK_DIR, f"{case_id}_mask.npy") if MASK_DIR else None

    print(f"[{i+1:03d}/{len(coliage_files)}] {case_id}", end="  ")

    # Verify mask on the first N cases (set VERIFY_MASK=False to disable entirely)
    do_verify = VERIFY_MASK and (i < 10)

    try:
        feat_vec, label = aggregate_coliage(
            coliage_path = coliage_path,
            mask_path    = mask_path,
            verify       = do_verify,
        )
    except Exception as e:
        print(f"\n    SKIPPED — failed after retries: {e}")
        failed_cases.append({"case_id": case_id, "filename": filename, "error": str(e)})
        continue

    print(f"label={label} (from tensor)")

    row = {"case_id": case_id, "label": label}
    row.update({FEATURE_NAMES[j]: feat_vec[j] for j in range(len(FEATURE_NAMES))})
    records.append(row)

if failed_cases:
    print(f"\n{'='*60}")
    print(f"WARNING: {len(failed_cases)} case(s) failed after all retries:")
    for fc in failed_cases:
        print(f"  {fc['case_id']}: {fc['error'][:100]}")
    print(f"{'='*60}")
    print(f"These cases are EXCLUDED from master_X.npy.")
    print(f"If this is due to a Drive mount issue, remount and re-run")
    print(f"this script — already-failed cases will be retried.")

    import json
    with open(os.path.join(OUTPUT_DIR, "failed_cases.json"), "w") as f:
        json.dump(failed_cases, f, indent=2)
    print(f"Failed case list saved to {OUTPUT_DIR}/failed_cases.json\n")

"""# Build master DataFrame and save"""

master_df = pd.DataFrame(records)
cols      = ["case_id", "label"] + FEATURE_NAMES
master_df = master_df[cols]

# Sanity checks before saving
assert master_df.shape == (len(records), 2 + len(FEATURE_NAMES)), \
    f"Unexpected master shape: {master_df.shape}"
assert master_df[FEATURE_NAMES].isnull().sum().sum() == 0, \
    "NaNs found in feature matrix — check CoLIAGe outputs!"

print(f"Master shape : {master_df.shape}  "
      f"({len(records)}/{len(coliage_files)} cases processed successfully)")
print(f"Label counts : {master_df['label'].value_counts().to_dict()}")
print(f"Feature range: min={master_df[FEATURE_NAMES].values.min():.4f}  "
      f"max={master_df[FEATURE_NAMES].values.max():.4f}")

# Save as both .npy (fast) and .csv (human-readable)
X   = master_df[FEATURE_NAMES].values.astype(np.float32)
y   = master_df["label"].values.astype(np.int32)
ids = master_df["case_id"].values.astype(str)

# Save this batch's results with a batch-specific prefix
np.save(os.path.join(OUTPUT_DIR, f"master_X_{BATCH_NAME}.npy"),   X)
np.save(os.path.join(OUTPUT_DIR, f"master_y_{BATCH_NAME}.npy"),   y)
np.save(os.path.join(OUTPUT_DIR, f"master_ids_{BATCH_NAME}.npy"), ids)
print(f"Saved batch {BATCH_NAME}: {X.shape}")